server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:mysql://java-stream-store-database.cwcxq6ok3cmm.ap-southeast-2.rds.amazonaws.com:3306/java_stream_store_database
    username: admin
    password: ${DATABASE_PWD}
  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true
  security:
    oauth2:
      resource-server:
        jwt:
          issuer-uri: https://dev-zhd4iadn.us.auth0.com/
          jwk-set-uri: https://dev-zhd4iadn.us.auth0.com/.well-known/jwks.json
auth0:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}
  audience: https://com.manolitsas.david/