server:
  port: 8080
  servlet:
    context-path: /
spring:
  datasource:
    url: jdbc:h2:mem:db
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
  h2:
    console.enabled: true
  sql:
    init:
      data-locations:
        - classpath:data.sql
  security:
    oatuh2:
      resourceserver:
        jwt:
          issuer-uri: https://dev-zhd4iadn.us.auth0.com/
          jwk-set-uri: https://dev-zhd4iadn.us.auth0.com/.well-known/jwks.json